<?php

namespace app\modules\v1\controllers;

use DateTime;
use Yii;
use yii\rest\ActiveController;
use yii\web\Controller;
use yii\web\Response;

/**
 * Compras controller for the `v1` module
 */
class ComprasController extends ActiveController
{
    public $modelClass = 'common\models\Compra';

    /**
     * Just to reinforce JSON format, as in some applications the format showed as XML, no good!
     */
    public function behaviors()
    {
        return [
            [
                'class' => \yii\filters\ContentNegotiator::className(),
                'formats' => [
                    'application/json' => \yii\web\Response::FORMAT_JSON,
                ],
            ],
        ];
    }

    /**
     * Checks request autorization/access
     */
    public function checkAccess($action, $model = null, $params = [])
    {
        if ($action === 'post' or $action === 'delete')
        {
            if (\Yii::$app->user->isGuest)
            {
                throw new \yii\web\ForbiddenHttpException($action .' - Action only available to registered users!');
            }
        }

        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }

    /**
     * Shows the user which actions and routes are available to use
     * @return array
     */
    public function actionHelp()
    {
        $help[] = array( 'allowed actions' => 'get,post,put');

        $get = array( 'action' => 'get' , 'routes' => array() );
        $get['routes'][] = array('todas as compras executadas pelo utilizador $id' => 'compras');
        $help[] = $get;

        /*
        $post = array( 'request' => 'post' , 'options' => array() );
        $post['options'][] = array('label'=>['Label'],'value'=>['value']);
        $help[] = $post;

        $put = array( 'request' => 'put' , 'options' => array() );
        $put['options'][] = array('label'=>['Label'],'value'=>['value']);
        $help[] = $put;
        */

        return array($help);
    }

    /**
     * @return mixed
     */
    public function actionAvailable()
    {
        $model = new $this->modelClass;
        $allCompras = $model::find()->where(['compraEstado'=>1])->all();

        return $allCompras;
    }
}
